GET http://localhost:8000/api/order-info-types
Accept: application/json

###

GET http://localhost:8000/api/all-categories
Accept: application/json

###

GET http://localhost:8000/api/products?category=1&characteristic=Крафт&priceRange=0:4
Accept: application/json

###

GET http://localhost:8000/api/admin/inventory
Accept: application/json
