DROP TABLE sessions;

ALTER TABLE users ALTER COLUMN phone_number SET NOT NULL;

ALTER TABLE products ALTER COLUMN amount SET NOT NULL;
ALTER TABLE products ALTER COLUMN in_stock SET DEFAULT FALSE;

ALTER TABLE orders ALTER COLUMN amount SET NOT NULL;
ALTER TABLE orders ALTER COLUMN end_status SET DEFAULT FALSE;