port: "8000"
domain: "localhost"

roles:
    guest: "0000"
    client: "0001"
    moderator: "1002"
    superAdmin: "2003"

db:
    username: "postgres"
    # set host to db service name when running a docker compose
    # host: "localhost"
    host: "db"
    # set inner docker port (5432 by default)
    # port: "5436"
    port: "5432"
    name: "postgres"
    sslMode: "disable"

redis:
#    host: "localhost"
    host: "redis"
    port: "6379"

minio:
    endpoint: "minio:9000"
    # endpoint: "localhost:9000"
    access_key: "minio99"
    secret_key: "minio123"