basePath: /
definitions:
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.RefreshTokensInput:
    properties:
      refresh_token:
        type: string
    type: object
  server.Category:
    properties:
      category_title:
        type: string
      id:
        type: integer
      img_url:
        type: string
    required:
    - category_title
    - img_url
    type: object
  server.Product:
    properties:
      amount_in_stock:
        example: 120
        type: number
      article:
        example: "000123"
        type: string
      category_title:
        example: Одноразові стакани
        type: string
      created_at:
        type: string
      id:
        example: 5
        type: integer
      img_url:
        example: https://google-images.com/some-img123
        type: string
      packages_in_box:
        example: 50
        type: integer
      price:
        example: 3.75
        type: number
      product_title:
        example: Стакан одноразовий Крафт 110мл
        type: string
      type_title:
        example: Стакан
        type: string
      units_in_package:
        example: 30
        type: integer
    type: object
  server.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  server.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role_id:
        type: integer
    required:
    - email
    - name
    - password
    - phone_number
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for AllianceCup Application
  title: AllianceCup API
  version: "1.0"
paths:
  /api/admin/new-moderator:
    post:
      consumes:
      - application/json
      description: registers a new moderator
      operationId: create account for moderator
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: CreateModerator
      tags:
      - api/admin
  /api/all-categories:
    get:
      consumes:
      - application/json
      description: get all categories
      operationId: get categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Category'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: GetCategories
      tags:
      - api
  /api/client/refresh:
    post:
      consumes:
      - application/json
      description: Gets a new access using refreshToken
      operationId: refreshToken from account
      parameters:
      - description: refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshTokensInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Refresh
      tags:
      - api/client
  /api/get-products:
    get:
      description: get products from certain category with params
      operationId: gets products
      parameters:
      - description: Category
        in: query
        name: category
        type: string
      - description: Size
        in: query
        name: size
        type: integer
      - description: Type
        in: query
        name: type
        type: string
      - description: Search
        in: query
        name: search
        type: string
      - description: Price
        in: query
        name: price
        type: string
      - description: Created At
        in: query
        name: created_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: GetProducts
      tags:
      - api
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: signs in account
      operationId: sign-in account
      parameters:
      - description: sign in account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    delete:
      description: ends session
      operationId: logout from account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - api/client
    post:
      consumes:
      - application/json
      description: registers a new user
      operationId: create account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
