basePath: /
definitions:
  handler.DeleteCategoryInput:
    properties:
      category_title:
        type: string
      id:
        type: integer
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.ItemProcessedResponse:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  handler.ProductIdInput:
    properties:
      id:
        type: integer
    type: object
  handler.RefreshTokensInput:
    properties:
      refresh_token:
        type: string
    type: object
  handler.allCategoriesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/server.Category'
        type: array
    type: object
  server.Category:
    properties:
      category_title:
        type: string
      id:
        type: integer
      img_url:
        type: string
    required:
    - category_title
    - img_url
    type: object
  server.Order:
    properties:
      created_at:
        type: string
      delivery_type_title:
        type: string
      order_comment:
        type: string
      order_status:
        type: string
      order_sum_price:
        type: number
      payment_type_title:
        type: string
      user_email:
        type: string
      user_firstname:
        type: string
      user_lastname:
        type: string
      user_middle_name:
        type: string
      user_phone_number:
        type: string
    type: object
  server.Product:
    properties:
      amount_in_stock:
        example: 120
        type: number
      article:
        example: "000123"
        type: string
      category_title:
        example: Одноразові стакани
        type: string
      created_at:
        type: string
      id:
        example: 5
        type: integer
      img_url:
        example: https://google-images.com/some-img123
        type: string
      packages_in_box:
        example: 50
        type: integer
      price:
        example: 3.75
        type: number
      product_title:
        example: Стакан одноразовий Крафт 110мл
        type: string
      type_title:
        example: Стакан
        type: string
      units_in_package:
        example: 30
        type: integer
    type: object
  server.ProductInfo:
    properties:
      description:
        example: Білий
        type: string
      info_title:
        example: Колір
        type: string
      product_id:
        example: 1
        type: integer
    type: object
  server.ProductInfoDescription:
    properties:
      description:
        items:
          $ref: '#/definitions/server.ProductInfo'
        type: array
      info:
        $ref: '#/definitions/server.Product'
    type: object
  server.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  server.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role_id:
        type: integer
    required:
    - email
    - name
    - password
    - phone_number
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for AllianceCup Application
  title: AllianceCup API
  version: "1.0"
paths:
  /api/admin/add-category:
    post:
      consumes:
      - application/json
      description: Adds a new category
      operationId: adds category
      parameters:
      - description: category info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: AddCategory
      tags:
      - api/admin
  /api/admin/add-product:
    post:
      consumes:
      - application/json
      description: Adds a new product
      operationId: adds product
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.ProductInfoDescription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: AddProduct
      tags:
      - api/admin
  /api/admin/all-orders:
    get:
      consumes:
      - application/json
      description: get orders by status
      operationId: get orders
      parameters:
      - description: Last item created at for pagination
        in: query
        name: created_at
        type: string
      - description: Sort by orders status
        in: query
        name: order_status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Order'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get Orders
      tags:
      - api/admin
  /api/admin/delete-category:
    delete:
      consumes:
      - application/json
      description: Deletes category
      operationId: deletes category
      parameters:
      - description: category info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: DeleteCategory
      tags:
      - api/admin
  /api/admin/delete-product:
    delete:
      consumes:
      - application/json
      description: Deletes product
      operationId: delete product
      parameters:
      - description: product id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.ProductIdInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: DeleteProduct
      tags:
      - api/admin
  /api/admin/new-moderator:
    post:
      consumes:
      - application/json
      description: registers a new moderator
      operationId: create account for moderator
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: CreateModerator
      tags:
      - api/admin
  /api/admin/update-category:
    put:
      consumes:
      - application/json
      description: Updates category
      operationId: updates category
      parameters:
      - description: category info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: UpdateCategory
      tags:
      - api/admin
  /api/admin/update-product:
    put:
      consumes:
      - application/json
      description: Updates product
      operationId: updates product
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.ProductInfoDescription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ItemProcessedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: UpdateProduct
      tags:
      - api/admin
  /api/all-categories:
    get:
      consumes:
      - application/json
      description: get all categories
      operationId: get categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.allCategoriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: GetCategories
      tags:
      - api
  /api/client/logout:
    delete:
      description: ends session
      operationId: logout from account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - api/client
  /api/client/refresh:
    post:
      consumes:
      - application/json
      description: Gets a new access using refreshToken
      operationId: refreshToken from account
      parameters:
      - description: refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshTokensInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Refresh
      tags:
      - api/client
  /api/get-products:
    get:
      description: get products from certain category with params
      operationId: gets products
      parameters:
      - description: Category
        in: query
        name: category
        required: true
        type: string
      - description: Size
        in: query
        name: size
        type: integer
      - description: Type
        in: query
        name: type
        type: string
      - description: Search
        in: query
        name: search
        type: string
      - description: Price
        in: query
        name: price
        type: string
      - description: characteristic
        in: query
        name: characteristic
        type: string
      - description: Created At
        in: query
        name: created_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: GetProducts
      tags:
      - api
  /api/product:
    get:
      description: get product full info by its id
      operationId: gets full product info
      parameters:
      - description: Product id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ProductInfoDescription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: GetProductById
      tags:
      - api
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: signs in account
      operationId: sign-in account
      parameters:
      - description: sign in account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: registers a new user
      operationId: create account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
